CLUSTAL multiple sequence alignment by MUSCLE (3.8)


gibbon           CATACTACTCCATACACCAAATTATCCAACTCCCCCAATCCAGAATAAACACCGACCATC
orangutan        CATACCACTCCACACCCTATACCATCCAACTTCCCCTATCCGAAACAAATACAAAACACT
sumatran         CATATCACTCCAAACCCCAAACCATCCAGCCTCCCCAATTCAAAACAAATACCAAGCACT
gorilla          CATACTACTCCACACACCAAATCATCTAGCCTCCCCAGTCCAGAACAAACACTGAAAATT
homosapiens      CATGCTACTCCACACACCAAGCTATCTAGCCTCCCCAATCCAAAACAAACATTAAACACT
chimpanzee       CATACTACTCCACACACCAAACTACCTAGCCTCCCCAATCCAAAATAAACATCAAACACT
bonobo           CATGCTACTCCACACACCAAGCTACCTAGTCTCCCCAATCCAAAATAAACATCAAACATT
                 ***   ****** ** * *    * * *    ****  * *  ** *** *   *  *  

gibbon           TTCACCCTCCACCACAATCAACACGCAACCAAACAACTCCTACGCACCTCTAAATCCACT
orangutan        TCCACCCCACCCCATAATCGACACATAACCAAACGACATCCGAATCCACCCCAATTTACT
sumatran         CCCACCCAACCCCATAACCAACATATAATCAAACGATACCCAAATCCATCCTAATTTACC
gorilla          TTCACCCCACGCCACAATCGATACGCACCCGAACAATACCAAAACCTACTCTAACCTACC
homosapiens      TTCATCCCACGTCATAACCAATACACGCCCAAGCAGTACCCAAACATACTCCAATTCACC
chimpanzee       TTCACTTTGTACCACAACCAATACACGTCCAAACAACACCCAGACATACTCCAATCCATT
bonobo           TTCATTTCATATCACAACCAATACACGTCCAAACAACACCCAGACATACTCCAATCCATC
                   **        ** ** * * *      * * *     *            **   *  

gibbon           CATCACACTTAAATATTAATCAAACGCAACAACACCCCCACATAAACCATCATACAACCC
orangutan        TTTTAGACACACACCCCTACCGCGCATACCAAAACCTCTACACGAGCAATCTCATACCCC
sumatran         CTCTAAACACACATTCCTACCACGCACACTAATACCCCTACACGAACGGTCCCATACCCC
gorilla          CACCAAACATACACTCCTATCATGCACACCAAAAACTCTACATAATAAACTCCCCACCTC
homosapiens      CACTAAACGCACACTCTTACCACGTATACCCAAAATCCCATATAGTCAACTCCACACCTC
chimpanzee       CACTAAACACATACTCTTACCACGCATACCAAAAACTCCATACAGTTAGCCCCACACCTT
bonobo           CACTAAACACATACTCTTACCACGCATACCAAAAACTCCATACAGTTAACCTCACACCTT
                     * **  * *     * *      *   * *   * * *             * *  

gibbon           ACGGCCCGCCCGCAACCCGATACCAAACCAACCTAGGAAACAACAACCCGACCACTATTA
orangutan        ATAACCCACCTACAATCCAGCCCCTAATTAACCCCGAAAACAAAAACCCGACCGCCATTA
sumatran         ATAACCCGCCCACAATCCAGCCCCCAACTAACCCTAAAAACAAAAACCCGACCGCCACCG
gorilla          ATAGCCCGCGCACGATCCAGCCATCAACCAATCTCAAATACAAAAACCCAACTACTATTA
homosapiens      ATAACCCGCCCACAATTCAGCCATCCACTAATCCCAAAAACAAAAACCTAACTACCACTA
chimpanzee       ATAGCCCGCCCACAATCCAACCATCCACGAATCCCAAAAACAAAAACCCAACTACCATTA
bonobo           ATAGCCCGCCCACAATCCAACCATCTACTAATTCCAAAAACAAAAACCCAACTACCATTA
                 *   *** *   * *  *        *  **      * **** ****  **  * *   

gibbon           AACAATCAGCGTGCGCACCCTACAGTACCTCACTCTCTCCTAGCCACCACCCAAACCATG
orangutan        GACGGCCAATTCACTCACCCTTTAACACCCCATTCTTCTCCCACTACAATTCGCGCAATA
sumatran         AACGACCAGTACACTCACCCTATAGCACCCTACTCTCCTCCCATTACAATCTACACTATA
gorilla          AATAACCAATACACACATCTTAAATTAACCTATCTCCTTTCCACTGCAATCCAAGTCACA
homosapiens      AACAACCAATACACATACCTTACGGCGACCTATCCCCCCTCCACTATAACCCAAACCACA
chimpanzee       AACAACTAATACGCACATCTTGTAACAACCCATTCCCCTCCCACTACAACCCAAGTTACA
bonobo           AACAACCAATATGCACATCTTATAACAACCTATCCCCTTCTCACTGCAACTCAAATCACA
                  *     *     *  * * *       *  *                *        *  

gibbon           CTCCGCCTGACCTCTGACTTATCACCATTCCACAGGTCCTAAACCCAAAAGCCTGGAACC
orangutan        CTCCAAGCGATCCTTGACGCATCACCACCCCCCCAACTTTAAGCAAAGCAACTACAAACC
sumatran         CTCCAAGCAACCCCTAACGCATTACCACCCCCTCAGCTTTAAGTCAAACAACTGCAAACC
gorilla          CTCCGAACAATTCCCGACCCACCACCACTCTTCATGCACTAAACCAGTTGACCTCAAATT
homosapiens      CTCCAATCAACTCCTGGCCCACCACCACATCTCACGCATTAAGCAAAATAACCTCAAGCC
chimpanzee       CTCCGATCGATTCCCGACCCACCACCGCGCTTCATATATCAAACCGAATAACCTCAGACC
bonobo           CCCCGATCGATTCCCGACCTACCACCACACTTCATATATCAAACCCAATGACCTCAAACT
                 * **     *       *  *  ***              **         *        

gibbon           CCAACTCCACTTTACGCAAATCAGTTCCTCACCCAACACACACAACCTCACCATACCACC
orangutan        TCAACTACGACCTACAACTCATAGTCTCTAATTTAACTAACATATCCCCAACGCAACATC
sumatran         TCAACTACAACCTACAACTCTCAATCTCCAATTTAACTAACACACCCCCAACGCAACATC
gorilla          CCCATTACACTTCACAACCCTTAGCCCCTAACCTAACCCACACAACTCCACCACAACATT
homosapiens      CCTACCACACCCCACAATCCTCAGCCTCCAATCTAACTCACACAGCCCCACCACAACATC
chimpanzee       GTTACCACACCCCATGACCCTCAACTCCCAATTTAATTCGCACAACCCCACCACAACATC
bonobo           GTTACCACACCCCGCGACCCTCAACTCCCAACTTAATTCACACAACTCCACCATAACATC
                    *   *              *    *  *   **    ** * *  ** *  * **  

gibbon           CCAACACCCTTAAAGCCCCCTTCTCCTAAACTCATACACACCTCCATTTCCAACCAGCAT
orangutan        CCCACACTCCCAAAACCCATTACTCGTATGTTCACACACATCCCTACCTCCAATCCACCC
sumatran         TCCACACTCCCAAAATCCACCACTCACATATCCATGCACATTCCTACCTCCGGTCCACCC
gorilla          ATCAAATTATCAAAACTCCCCCTCCACAAATTCACACACATTACCATCTACAACCAACCC
homosapiens      ATCACATTCCTAAAACCCCCCCCCCCCAAACCTACACACATCTCTATTTTCAACCAACCT
chimpanzee       ACCACATTCCCAAGATTCCCTCCCCACGAACTTATACACATTCCCATTTTCAACCAATCC
bonobo           ACCACATTCCCAAAATTCCCTCCCCATGAACTTATACACATTCCCATCTTCAACCAATCC
                    * *     **    *      *        *  ****   * *  * *   *     

gibbon           CAACCAAAAAGCATACACACAAATCCATCTCACCTACAATGCACAACTCCTCCATCCCCC
orangutan        CAACCCAAAAATGTACACACACATTCGTTCAACCCACAAGACGCAACCCCCTCATTCCCC
sumatran         CAACTCAAAGATGCACACACACATCCGCTCAGCCCACAAAACGCAACCCCCTCACTCCCC
gorilla          TATTCCAAAAACATATACATAAATTCGATTGACCCATAAAACATAACCCCCTCACCTCCC
homosapiens      TATCCCAAAAATACATGCATGAATCCAGTCGAACTATAAAACACAAATCCCTCACCTCCC
chimpanzee       TATTCCAAAAATATACGTATAAATCCAGTCGAACTATAAGACACCACTCCCTCACTTTTC
bonobo           TATTCAAAAAACACACGTATAAATTCAGTTGAACTATAAAACACAACTCTCTCACTTTTC
                  *    ***     *   *   ** *       * * **  *   *  *   **     *

gibbon           CCGATCACCACTACCCAGCCAGCACACCCTCCGAACGTCCAGACAAGTTATCTATTCACC
orangutan        CCAATCACTACCACCTAATCACCACAACTCCCCACCAACCAGACAAACCAACTACCTACC
sumatran         CCAATCACTACCACCTAATCACCACAACTCCCCACCAACCAAACAAACTAACTACCTACC
gorilla          CCAACCACTACTATTCAATCAGCACAGCTTCCTACCACCCAAACGAATCGGCCATCCATC
homosapiens      CCAATCACCACCACTGAATTAGCACAACCTTCCATCGTCTAAACAAACCAACCGCCTATC
chimpanzee       CCAACCACTATCACTGAATCAACACAGTCTCCCATCACCTAAACAAACCGACCACCCACC
bonobo           CCAACCGCTATCACTGAATCAACACAGCCTCCCGTCACTTAAACAAACCAACCATCCACC
                 ** * * * *  *   *   * ****     *   *    * ** *     *     * *

gibbon           CCCCACAACACCCAACCCCACCACGCCTATACCCATCTCTATTGACACCCAACCTCCCAA
orangutan        TCCCAAAATACCCAACCCCGCAACACCCACGCTTATCCCCATCCATACCCGATCTCAATA
sumatran         TTCCAAAATACCCGACCCCGCAACACCCACGCTTATCCCCATCCATATCCAATCCCGACA
gorilla          CCTCATAATGCCCAGCTTCATCACACCTATACCCACCTCCACTCTTACCCAACTTCATAA
homosapiens      CCTCAAAATATCCAACCTCATCACACCCACACCCACTCTCACCCATATCCAACTCCACAG
chimpanzee       CCCTAAAATACCCAACCTCACCACACTCACACTCACATCCGCTCACACCCAGCCTCATGG
bonobo           CCCCAAAATACCCAACCTCACCATACTCACACTCACATCCACTCACACCCAACCTCGTAG
                     * **   **  *  *   *  *  *  *  *           * **     *    

gibbon           AATCTCCCTACTCATCACTACATTCAAAAAGATTACAACCTAAAATAACAACCCCAAGGC
orangutan        CACCCTCCCATCAATTAACACATCCAAATAAATCATAACTCAAAACAATAATCACAGGAC
sumatran         CACCCCCCCGCCCATTAACACATCCAAACAAATCATAACCCAAAACAATAACCACAGAGC
gorilla          CATCGCCCTATTAATCGACGCACTCAAAAAAATTACAACCCAAAACAACAACCATGGAGT
homosapiens      CATCGCCCTACCAATCAATACACTTAAAAAAATCGTAACCTGGAACAAAAACCACGGAAT
chimpanzee       CATCGCCCTACCAATCAACACATCCGAAAAAATCGTAACTTAAAACAAAAGCCACGAAAT
bonobo           CATCGCCTTACCAATCAACACACCCAGAAAAATCATAACTTAAAACAAAAGCCACGGAGT
                  * *  *      **     **     * * **   ***    ** ** *  *       

gibbon           ACGGCTCACAACAACTACTCAAAACTCCCCCTACCCCCCCACATCCCAACAAAACCTCTG
orangutan        ACCACCTGTGATAACTCTTCAAAGCCTCCCCCACCCACCCACGCCTCAACAGACCCTCCA
sumatran         ACCACCCATGATAACTCTTCAAAGCCTCCCCCACTCACCCACGCCACAACAAACCCCCCA
gorilla          ACTACTTATAATAACTTTTCAAAACCTTTTCCACTTCCCCACGCCTCAACAAGATCCCCA
homosapiens      ACCACCCACAATAACTTCTCAAGTCCTTTCCCACTCTCCCACGTCTCAACAAAATTTCCA
chimpanzee       ACCACCCACAATAATTTCTCAAATTCTCCTCCATCTCCCTACACCTCAACAAAATTTTTA
bonobo           ACCACCCGCAATAACCTCTCAAATTCTTCTCCATCTCCCCACGCCTCAACAAAATTTTTA
                 **  *     * **    ****        * *    ** **  * *****         

gibbon           TCAAAACCAACGTTTTACACCCGCCCCTCGACGCCCCCTTCAACCTAACGCCATACCTGG
orangutan        TCAGAATTATCAACCCATACCCATACCCCAACACCCTCCCTAACCTAGCACCGTTCTCAG
sumatran         CCAGAGTTATCAGCCCATACCCACACCCCAACGCCCTCCCCAACTTAACACCGCTCCTAG
gorilla          CCAAAGCCACCGCTTCACGCCCATAACCTGATACTCCCCTCAACTCAACACCACCCTTAG
homosapiens      CTGAAACCATCGCCCCACCCCCACACCTCAACGCCTCCTCCAATCCAGCACCGCCCCCAA
chimpanzee       CCGAAACCATCGCCCCACTTCAACGTCTCAACGCCCCCTTTAACCTAATACCACCCCCGA
bonobo           CCGAAACCATCGCCCCACTTCTATATCTTAACGCCCCCTTTAACCTAATACCACCCCCAA
                     *   * *     *   *     *   *  *   *   **   *   **   *    

gibbon           CTTTCGTAAATAAAGTCACTACTCAGTTATACTCTAATAAACCACAATCCCGTAAACCCA
orangutan        CCCTCGCAAACAAACCTACACCCTAACCACACCTCAACACACCGCAACCCAACGAACACC
sumatran         CCCTCGCAAACAAACCTACCCCCCAACCACATCTCAACACACCACAATACAACGAGCACC
gorilla          CTCCTACCAACAAATCAACTCCCCAACTATACCCTAATACATCACAATTCAACAAACACC
homosapiens      CCCCCATCAACAAACCGACTCTCTAAACGTACCTTAATAAACCGCAATCCAACAAATATC
chimpanzee       CCCCCACCAATAAATTAACTCTTCAGCCATACCTTAATAAATTACAATTCAACAAACATC
bonobo           CCCCCACCAATAAACCAACTCTTCGGCCATACCTTAATAAATTACAATCCAACAAACATC
                 *       ** ***   **           *    ** * *   ***  *    *     

gibbon           GCACACACCTACAGATCCACAGCTGCCTCTAATCAAATCAACTACCACCCCTAAACCTGT
orangutan        ACACACACTCAAAAATTCACAACTATCCCTGTCCAAACCAACCACTAACCCCAAATCAGC
sumatran         ACACACACTCGAAAGCTCACAACTATCCCTGTCCAAACCAACCACTAACCCCAAATCAAC
gorilla          GCGCACACCCAAAAACCCGCAACTACCCTTGCTTAGACCAACTACCAATCTCAAACCAAC
homosapiens      ATACACTCCTAAGGACCTACTACTAACCTCGCCCAAATCAACTACCAATCTTAAACCAAC
chimpanzee       ACACACTCCCAAAAACCCACAACTAACCTTACCCAAACTAACTACCAATCCCAAACCAAC
bonobo           ACACACTCCCAAAAACTCACAACTAACCTTACCCAGACCAACTACCAATTTTAAACCAGC
                    *** *           *  **  *       * *  *** ** *     *** *   

gibbon           GAGTCACCAAACCACAACCCCCCTAAAACAGTCGACACAGGCCAGAACACACCCAATCAA
orangutan        GAACCACCAAACCGCAACCCCCACAAAACAACCAACACAGAATAGAGCATACCCAGTCAA
sumatran         AAATCACCAAATCACGACCCCCACAAAACAACTAACACAGAATAGAACACACCCAACCAA
gorilla          AAGCCACCAACACACAACCCCTACACAACAACCAATACAAATTAGAACGCACCTAACCAA
homosapiens      AAGCCACCAGCCCACGATCCCCAGCCAACGACCAACACAAGCTAAAACACACCCAATCAA
chimpanzee       AAGCCGCCAACCCGCAACCCCCAAACAACAATCAGCATAAACTTAAACACACCCAACCAA
bonobo           AAGCCACCAACTCACAACCCCCAAGCAATAATCAACATAAACTTAAGCACACCCAACCAA
                  *  * ***   * * * ***     **        * *      * *  *** *  ***

gibbon           GTCCAACATTCAACCCTTATTAACCTCCACCCCAAAACACAGCCCACCTAACACACCAAG
orangutan        TCACGACACCCAACTCCCATCAACCCTCACCCCACAACACAACTTCTCCAACACACACAA
sumatran         CCATAACACCTAACTCCCACCAACCCCCACCCTATAACACAACTCCCCCAACACACACAA
gorilla          CAATAGCATTCAACTCCAACCATCCCCCACTCTAAAACACAACCCAACCAATATATATAG
homosapiens      CTACGACATTCAATTCCAATCACTCCCCACTCCAAAGCGCAACCCGATCAACACACACAA
chimpanzee       TCATGATTTTCAATTCTAATTATCCCCCACTCCGAAACGCAATTCAATCAACACACATAA
bonobo           TCACAATTCTCAATTCTAATTATCCCCCACTCCGAAACACAATTCAATCAATACACATAA
                            **  *  *  *  *  *** *   * * **        ** * *   * 

gibbon           CAAATACCACCCCAAACTATAACAGATCACGACCCTCCGACAATTACTCCCCCCTTCCAC
orangutan        TAAACATTACTCCAAACTTCAATAAACCGCAACCCCACCATAGCTATCCCCTCCCCCAAC
sumatran         CAAACATCACTCCGGATTACAATAAACCACAACCCCTCTGTAACTATTCCCTCCCCCAAC
gorilla          CAATCATCACCTCAAATCTCAATAAATCATAGCCCCCCAACAGCTACCTCTCTTCTCAAT
homosapiens      CAAAAACCATCTTAAACCACAATAAGTTATAGTCTTCCAACAGCCATCCCTCCCCCCAAT
chimpanzee       CAAAAATTACTCCAAATCACAATAAGTTGTAATTTTCCAACAATCACTTCTCTCCCCAAC
bonobo           CAAAAATTACTCCAAATCACAATAAACTATAATCTCCCAACAACCACTTCTCTCCCCAAC
                  **  *  *      *    ** *             *   *   *   *      * * 

gibbon           TACGCCCGCTCTCAAACCCCCTCCAAACCCATACCCCCACCTATATCATGTAGCATCCCC
orangutan        CGCAACCCCCCTTAAACCTGCGCCAAACCCACACCTCTACTCATACTATACAATGCCCCC
sumatran         CACGACCCCCCTCAATCCTACACCGAACCCACATCTCTGCCCACGCTACACAGTGCCCCC
gorilla          TACACTCGCCCCTGATCCTCTTTCAAATCTACACCCCCACCTGTGCCATACAACACCCCC
homosapiens      TACACCTATCCTTCATCCTCCCCCAAATCTACATCTCCACCCACGTTATGTAATGTCCCT
chimpanzee       TACACCCACCCTTAATCCTCCCCCAAATCCACATCCCTACCCACACCATACAATATCTTC
bonobo           TACACCCGCCCTTAATCCTCCCCCAAATCCACATCCCTACCCACGCCATACAATATCCCC
                   *       *   * **     * ** * * * * *  *       *   *    *   

gibbon           AAACGCATCAAAAACCCATCCTACACCTTAAACTTACACCCGCCGCCAAATACACCAATC
orangutan        AAGAACACCAAAAATCCACCCCCCAACCTAAGCCCATACCCACCACCTAACACATCAACC
sumatran         AATAATACCAAAAACCCATCCCCCAACCCAAGCCCACACCCACCACCTAACATATTAACC
gorilla          AAGTACATCAAAAATCCACTCCTCGCCCCAAACCCACTTCCACTACCAGACACACCATTC
homosapiens      AAGAACATCCAAAATCCACCCCCCACCCCAAACCCACTCCCGCCACCAAACACGCCAACC
chimpanzee       AAAGACATCAAAAATTCATCCCCCACCTCAAGCCCATCCCCACTATCAAACATACCAACC
bonobo           AAAAACACCAAAAATTCATCCCCCACTTCAAACCCATCCCCACTACCAAACATACCAACC
                 **    * * ****  **  *  *     ** *  *   ** *   *  * *    *  *

gibbon           CATCAAATCCCACACCCACCCCTCCCTCAATTCCACACCCACACCTACTCAACATTCTCC
orangutan        TCCTAACCTTTATACCCAACCCTCTCCCAGCTCCCCACTCACACTCACCCAACACTTTCA
sumatran         CTCTAACCCCTATACCCAATCCCCTCCCAACTCCCCATCCACACTCACCCAACACCCCCA
gorilla          ACCCAATCCCCATACTCACCCCCCTCCCAACCTCCTACCAGCACCCATCCAACACCCCCC
homosapiens      ACCTAACCCCTACATTCACCCCTCCTCCAACTCCCCACCGACATCAATCCAACACCCTCC
chimpanzee       ACCCGGCCCCCACACTTGCCCCCCTCCCAATTCCCCACCCATATCCATCCAACACTCTCC
bonobo           ACCCAGCCCTCACACTTACCCCTCTCCCAATCCCCCACCTACATCCATCCAACACTCCCC
                            * *      ** *   **    *  *     *   *  *****    * 

gibbon           ACACAAACCGCTCCAACAACTAGCAACACAACCCACCAATACAGCACCCAATCCACACTC
orangutan        GTACAAACCACCCCAACAACCAACAATACAACCCACTAACACAGCAGCCAATCCTAAACT
sumatran         ATATAAACCATCCCAACAACCAACAACATAGCCCACTAACGCAACATCCAATCCTAAACC
gorilla          ACACAAACCACTCCAACAACCAACAACACGACCCGCCAACACAATATTCAATCTCTAACT
homosapiens      GTATAAACCATTCCGACAAACAGCAATACAACCCACTGACATAACAACCAACTCCCAACT
chimpanzee       GCACAAACTGCTCCAACAACCAACAATACAGCTCACCAACGCGACAACCAACCTCTAACC
bonobo           GCACAAACTGCTCCAACAACCAGCAATACAGCCCACCAACCCAACAACCAACCTCTAACC
                   * ****    ** ****  * *** *   * * *  *      *  ***     *   

gibbon           CTCCCATCTCGCAACGCTACACGAAACTCACCCCAACACCCCCCTACACCAAATCCCCAA
orangutan        CTCCAATCCTATAACTCCACTCAAAATCCGACCCCCTACTCCCCTATACCACACTTCCCA
sumatran         CACCAACCTTACAATACCACACAAAATCCGACCCTCCACCCCCCCACACCACACTTCCCA
gorilla          CCCTCACCCCACAACCTCATACAAAACCTACCCCCTCACCCCCCCACACCACACCTCGCG
homosapiens      CTCCCGCCTTACAAACCCACGCAGAACCCAACCCTCTACCCCTCCACACCCCATCCTCCA
chimpanzee       CCCTCACCCCACAAATTCACACAAAATCCAACCCCCCATCCCCCCACATCTCACTCCTCA
bonobo           CCCTCACCTCACAAATTCACACAAAATCCAACCCCCCATCCCCCCACATCTTACTCCCCA
                 * *    *    **    *  *  **     ***   *  ** * * * *  *       

gibbon           ACAAACACCCACCGCCTCGTTCACCTCCCACAACTACACATAGCCTTAGACAACCAAACC
orangutan        AAAAACAACCACCACCCCATCCACCACCTGCAACCACCCACAACCCCAAATAACCGATCA
sumatran         AAAAACAACCACCACCCCATCCACCACCTACAATCACCCACAACCCCAAATAACCAACCA
gorilla          AAAAACAACCAACACCCCACCCACCACCCACAATCATCCATCATCCTAAACCATAAATTC
homosapiens      GAAAACAACCACCACTTCACCCACCTCCCGCAATCACCCATCACCTCAAACCTCAAACCC
chimpanzee       GAAAACAACCACTACCTCATCCACCACCTACGACTATCCACCACCCCAAACCCCAAATCA
bonobo           AAAAATAACCACTACTCCACCCACCACCTGCGGTTATCCATCACCCCAAATTCCAAATCC
                   *** * ***   *  *   **** **  *    *  **    *  * *      *   

gibbon           CAAACCACCATAGACGATCAACGCGCACAAACAGTCAACAAAGACCATCCTAAGACAACC
orangutan        CAAACCTCCACGAGCAACCAACACACACACCCCATCCATAAAAACCCTTTTCAAACAACT
sumatran         CAAACTCTCGCGAGCAATCAGCACATATACCCTATCCATAGAAACCCCCCTCAAACAGCC
gorilla          CAAATTTCCACAAACAACCAACAACCACACACCCCACACAAAAACCCCCCTGAAACAACC
homosapiens      CAAACCCCTACAAACAATCAACAATTACACACCCTACACAAAAACCTTCCTAAAACAACC
chimpanzee       CAAACTCCCACAAACAATCAACAGTCACACACCCCACACAAAAACCCCCCCAAAACAACC
bonobo           CAAACTCCCACAAACAATCAACAGTCACACACCTCACACAAAAACCCCCCCGAAACAGCC
                 ****          * * ** *    * *  *     * * * ***      * *** * 

gibbon           CACAATAACCCACACAACAACCCGCCCACCACCAACAGACAAACACCAAACACCCCACCT
orangutan        CTCACTAACTCGCACCACAACCCGCCTATCACCAATAGACAAACACTAAACGATCCACCC
sumatran         TTCTATAACTCGCACCACAACCCACCTACCACCAATAGACAAACACCAAACAGCCTGCCC
gorilla          GACACGAACACGCACAACAATCTACCTATCACCAACAGACAAATACTAAATACCCCACCC
homosapiens      AACACAAATCCATACAACAGCCCACCTACTACAGACAGTCAAATACTAAACACCCTACCC
chimpanzee       AACACAAACCTACACAATAACCCACCTACCACAAACAGACAAATACCAAACATCCTATTC
bonobo           AACACAAATCCACACAACAATCCACCTATCACAAACAGACAAACACCAAACACCCTACCC
                   *   **     ** * *  *  ** *  **  * ** **** ** ***    *     

gibbon           CAAGTCCCAAGCCCAACAAATAACCCCTCCCACACTCTCCAAACCCCACCCACCCCGCCA
orangutan        CAAACTTCCAAACCAACAACCAACCCCCTCCCCACCCTCTAAACCCCGCCCACCCCACCA
sumatran         CAAACTCCCAAACCAACAACCAACCCTCTTCCCACTCTCCAAACCCTGCCCACCCCACCA
gorilla          GAAACCTCCAACCCAGCAACAAACCCCCCCCACATCTTCAAAACCCCACCCACTCTACCA
homosapiens      GAAACCTCCAACCCAGCAACCATCCCACCCCGCATCCCTTAAACCCCACCCGTCCCACCA
chimpanzee       GAAGCCTCCAACCTAACAACCTACTCCCCCCACACCCTCCAAACCCCACCCACTTCACCA
bonobo           AAAGTCTCCAACCCAACAACCTATTCCTTCCACACGCCCCAAACTCCGCCCACTTCACCA
                  **    * *  * * ***      *    * **      **** *  ***      ***

gibbon           TCGTATCACCCCCAAAAAAACTCCCACCAGAAACAATATACTGCTCAAAAATGCCATCCC
orangutan        CCACAACACCCCCCAAAAACCACCCACCAAAAACAGCACACCACTCGAAAAAACCATCCC
sumatran         TCACGACACCCCCCAAAAATCACCCACCAGGGACAGCACATCACTCGAAAAAACCTTCCC
gorilla          CCACCTCACTCCCCAAGGAACACCCGCCAAAAACAACATACCGCTCAAAAAGGTTCTCCC
homosapiens      TTACCTCACTCACCAAGAAACACCCGCCAGAAACAACATACCACCTAAAAAAATCCTCCC
chimpanzee       TTACCCCACTCACCAAGAAACGCCCACTAAAAACAACACACTACTCAGAGAAATCCCTCT
bonobo           TTACCTCACTCACCAAAAAACGCCCACTAAAAACAACACACTACTTAAAGAAATCCCTCT
                       *** * * **  * * *** * *   ***  * *   *    * *       * 

gibbon           CCTAAAGCCAGCAAAGCATAAATCTAAAACTACCCCCCAAGAAACAACTCATTCCACCAC
orangutan        CCCAAAGCAAACAACGTACAAATCAAAAACCACCCCTCAAACAATACTCGACCACACCAC
sumatran         CCCAAAACAAATAAAATACAAATTAAAAACCACCCCCCAAACAATGCTCTACCATACCAC
gorilla          CCCAAAACCAGCAAAACATAAATCCAAAACCGCCCCCTAAATAACACTTCATCACCCCAT
homosapiens      CTCAAAACCAACGAAACGCAAATCCAAAGCCACCCCTCAGGCAACACCCCACCACCCCAC
chimpanzee       CTCAAAGCCAACGAAACGCAAATCTAAAGCCATCCCTTAAATAACACTTCGTCACCTCAT
bonobo           CTCAAAACCAACGAAACGCAAATCTAAAACCGTCCCTTAAATAACACCCCATCACATCAC
                 *  *** * *   *     ****  *** *   ***  *   **             ** 

gibbon           CACATACCTGACCACCACCATCACCCCCAATCCACCCCACACACCATAACAAACCACCCC
orangutan        CACACACTCAACCCTTATCAAAACCCCCAACCACCCCCACACATCACAATAAACCACCCC
sumatran         CACATACTCAACCCCTATCAAAACCCCCAACCACCCCCACACACCACAATAAACCACCCC
gorilla          CACGCATTCAATTCCTATCAAAACTCCCTACCAACCCCACGTACTACAATATATTATCCC
homosapiens      CACACACTTAACCCCTACCAAAATCACCTACCAATTCCGCATGCCGCAATAAACCACCCC
chimpanzee       CACACACTTAACCCTTACCAAAACTTCCTACCGATTCCATATACCGCAATAAATCATCCC
bonobo           TACACACTTAACCCTTACCAAAACTGCCTACCGACTCCGTATACCGCAATAAATCATCCC
                  **  *    *     * **  *   ** * *    **         ** * *  * ***

gibbon           ACGCCAAACCAACCAAAAAATTTACCATCCTCAGCTCATACCCCCCTCATACTCAACACA
orangutan        ACGCCAAATCGACCAAAAAACCCACTACTCTCAACCCATACCCCCCCCACATTAAGCCCA
sumatran         ACGCTAAATCGACCAAAAAACCCACTACCCTCAACCCGCACCTCCCCCACGCTAAGCCCA
gorilla          ACGCCGAACCGACCGAACAATTCATCACCCTCTACCCGCACCCCTCCCACTTTAAACCCA
homosapiens      ACACCAAACCAACCAAATAATCCACTACCCTCTACTCGCACCCCTCCTACACCAGACGCA
chimpanzee       GCACCAAACCAACCAAACGATCCACTACCCCCTACTCACACCCCTCCTACGCTAGACACA
bonobo           ACACCAAACCAACCAAACGATTCACTACCCCCTACTCACACCCCTCCCACACTAGACACA
                  * *  ** * *** **  *   *  *  * *  * *  *** * *  *       * **

gibbon           CCCGGAAAACAACCCATGAAAATCCCAATTCATCCAAACACATCAACTCCCCATCGGATA
orangutan        CTCAGCAAACACTCCACACAAACCCCAACTCATCCAAACACATCAACCCCCCATCAGACA
sumatran         CTCAGAAAATACTCCACACAAACCCCAACCTATCCAGACACACCGACCCCCCATCAGACA
gorilla          TTCAACAAACAATTCACACAAATCCCAACCCATCCAAATACACCAACCCCCCACCAAACA
homosapiens      TTCAACAAACGACTTATACAAACTTCAATCCGTCCGAACACACTAATCCCCTACCAAACA
chimpanzee       TCCAACAAATAATTCACACAAACCCCAACCCACTCAAATGCATCGATCCCCCACCAAACA
bonobo           TCCAACAAATAATTCACACAAACCCCAATCCACTCAAACGCGTCAATCCCCCACCAAACA
                   *   ***      *   ***   ***      *  *  *    *  *** * *  * *

gibbon           CCCCCATAAAAAAACGTAAGAACCTCCGCAACCGATCTACCACCCAAAAGCTCACACACC
orangutan        CTCCCATATAATACCAAAAAAACCCCCACAACCAACCAACCACCTAAAAACCTATACAAC
sumatran         CCCCCATATAACACCAAGGAAACCCCTACAACCAACCGACCACCTAAAAACCTATACAAT
gorilla          CTCTTACAAAGCAATATAAAAACCTCCAGAACCACCCAGTCACCCAAAAACTGACACATC
homosapiens      CTTCTACAAAACAGTAAAAAAACCTCCACAGTCACCTGACCGTTCAAAAACCCACACACT
chimpanzee       CTTCTACAAAATAAAGAAAAAACCTCTATAATCACCCAACCACCCAAAAACTTATACACC
bonobo           CCTCTACAAAATAATGAAAATACCTCCATAATCACCCAACCACCCAAAAACCCATACAAC
                 *    * * *  *        *** *   *  *       *    **** *  * ***  

gibbon           AGACACCCCCTACATCGACCACAGCACAACATAACCACCCACAAGCAAACCACCCCCCAC
orangutan        AAACACCCCCCATATCGACCACAACACAACACGACCACTCAAAAAAAACCCACCTCCCAC
sumatran         AGACACCCCCCATATCAACCACAACACAACACGACCACCTAAAAAAAAATCACCTCCCAC
gorilla          GAATACTCCTTACACCAACCACAACATAACGTAACCACCTAAAAAATAATCTTATTTTGC
homosapiens      CAACACTCCTCACACCAACTATAACACGACACAACCATCCAAAAAATAGCCTCACTTTAT
chimpanzee       AAGCACTCCCTACGCTAACCACAACACAACACAACCACCCACAAAACAATCTCACTTTAC
bonobo           AAGCACTCCCTACGCTAACCACAACACAACACAACCACCCACAAAATAACCTCACTTTAT
                     ** **  *     ** * * **  **   ****   * **   *  *         

gibbon           CCCGAACCACAACCGTCCCACAAATCTACAACAAGCACACCAAAAACACAACACACAACA
orangutan        CTTCGATCACATCCACTCCACAGACCCACAGAAAACACAACAACAGCGCAACCCACAATC
sumatran         CCCCGATCACACCCACTTCACAAACCCGCGGAAAACACAACAACAGCGAAACCCGCAACC
gorilla          TTTCCTTCACAACCACCCCACAAATTTATAGAAAATACCCCCCCAATACAACCCACAGTT
homosapiens      TTTCATTCACAACCACCCCACAAATCCACGAAAAACATACCCCCAACGCGACCTGCAGCT
chimpanzee       TCCCATTCATGACCACCCCACAAATCCACGAAAATCATACCCCCAACACAATCCACAATC
bonobo           TTCCATTCACGACCACCCCACAAATCCACGAAAATTACACCCCCAACACAACCCGCAATC
                        **   **    **** *        **  *   *   *     *    **   

gibbon           TAACAGCAACTCATCACCCCTCCACCCACACCCCACGGTCACCCAAAGAGTTACACAAAG
orangutan        TGACAACCTTTTCACACTCTCCCCCCCACATCCCACAACCGTCCAAAAAACCCCTCAAAA
sumatran         TAATAATCTCTCCACGTTCCCCCCCCCACACCCCACAACCATCCAAGAAGCCCCACGAAA
gorilla          CAACAATCCCTCCCTGCCCCCCCCTCTACATCCCTCAAACACCCAGAAAGCCCTACAAAA
homosapiens      CAACAACTCCCCCCCACCCCCTCCCCCACACCCCACAACCATCCAAAAAGTCCCACAAAA
chimpanzee       CAACAATTCCCCCCCACCCTCTCCTCCACACCCCATAATCATTCAAAAAACTCTACAAGA
bonobo           CAACAATTCCTCCCCACCCTCTCCTCCCCACCCCGCAATTACTTAAAAAATTCTACAAAA
                   * *             *   *  *  ** ***          *   *      * *  

gibbon           TTACAAAGCCCCAACCCCACATCAACCCCTATCAACCGCACTTAATTAACTAAACAGACA
orangutan        CCACAACATCCCAACCACATATCCACTCCTTCCAACCAACCCCAACTAATCAAACAAACA
sumatran         CCACAAAACCCCAACCACATATCCACCTCTTCCAATCAACCCCAACCAACCGAACGAGCA
gorilla          TTATAAGATCCCAATCCCATTCCCACCCCTTCCAATCAACCTCAATCAATCCAGCGAACA
homosapiens      TTATAAAACCCCAACCTCGCCCCTACCCCCTCCAACCAATTCCAATTAATCCTACAAACA
chimpanzee       TCACAAAACCCCAATCTCATCCCTACCCCCCCCAATCAACCCCAATCAATCCAGCATACA
bonobo           TTACAAAACCCCAATCTCATCCCTACCTCCCCCAATCAACCCCAATCAATCCAACAAACA
                   * **   ***** * *    * **  *   *** *      **  **     *   **

gibbon           AACAGACAAACAACCTACACGTCAAAAAGACGCAGATCCCTAAACGAAATAACACATCAC
orangutan        AAAAAACAAGTAATTCGCGCATCAACAAAACACAAATCAACAAACAAACCAACACACCCC
sumatran         AAAAAATAAATAATCCACACATCAAAAAAACACAAATCAACAGGCAAACCAGCACACCCC
gorilla          AAAAAACGACCAACTCACATACCAAGAAAACGCAAACCAATAAAGAAACCAATATACCAC
homosapiens      AAGAAATGACCAACCCACATGCTGAAAAAACACAAACCAATAAAAGAACCAACATACCAC
chimpanzee       AGAAAACAACCAATTCACACCCCAAAAAGACACAAACCGATAAAAAAACTAATATACCAC
bonobo           AAAAAACAACCAACTCACACCCCAAAAGGACACAAATCAATAAAAAAACTAATATACCAC
                 *  * *  *  **    *      * *  ** ** * *   *    **  *  * * * *

gibbon           CCTATCCCCGAACTCGCCCCATCCCACTCCCCACACCAGGACAGCCAACAACACCACCAC
orangutan        CCTTCCCCCCAACCCACCCCGCCCCCTCCCCCAACCTAAAACACGCCATAATATCACCAT
sumatran         CCCACCCCCCAACCTACCCCGCCCCTTCCCCCAACCTAAAACACACCATAACACTACCAC
gorilla          CCCACCCCTCAATTCATTCTATTCCATTCCCCAGCCCAAATCACACTATAACGCCACCAA
homosapiens      CCCATTCCCCAATTCACCCCATCCCACTCCCCAACCCAAATCACACGACGACACCACTAA
chimpanzee       TCCATCCCTCAATTCATCCCACCTCGCCCCCCAATCCAAATTATACCACAACGCCACCAA
bonobo           TCCATCCCTCAATTCACCCCACCTCATCCCCCAACCCAAATCATACCACAATGCCACCAA
                  *    **  **      *     *   *****  * *    *  * *  *    ** * 

gibbon           TAAAACCATAATCCACAATAACCCTAAAACCCCTATACCCTATCTTAGTCAGACACACAC
orangutan        CAAAAACCCAACTTACCACAATACAAATATCCCCACTCCCCACTCCCACCAAACACACAT
sumatran         AAAAAACCCAACTTACCACAACACAGATATTCCCACTCCCCACTCCCACCGAGCATACAC
gorilla          AAAAACTCCAACCCACCACAACACAAACACTCCCACATCTCATCCCAACCACATACGTAC
homosapiens      AAAAACCCTAACCAACCATAACACAAACATTCCCACATCCCGTCCCAACCAAACGCACAC
chimpanzee       AAAAACCCCGATCCACCATAACGCAGATATTCCCACATCCCGTCCCAGTCAAACGCATAC
bonobo           AAAAACCCCAACCCACCATAACACAGATATCCCCACACCCCACCCCAGTCAAACGCATAC
                  ****     *   ** * **  *  * *  ** *   *          *        * 

gibbon           TACCCAACCCCACTATCCCCCCACAACTACTTCAAAACAATCAAAACTCATCCACCACTT
orangutan        TACCAAGCCCCATTCACCCCCCACACTTATCCAAAAACAGTCGAAACTTAACAACCACTC
sumatran         TACCAAACCCCACTCACCCCCCACGTCTACCCAAAAGCAATCAAAACCCAACAACTACTA
gorilla          CACCCAAACCCATCAACCTCCCACAATTACCCAAAGACAACTAGAAATCGCCAACTGCTT
homosapiens      CACCCAACCTCACCAATCTCCCACAACTACCCAAAATCAATTAAGATTCACCAACTACTC
chimpanzee       CACTCAACCCCACCAACTCCCCACAATCACCCAAAAGCGGTCGAAACTCACCAACTACTC
bonobo           CACTCAACCCCACCGACCCCCCACAATCACCCAAAAGCGATCGAAAATCACCAACTACTC
                  **  *  * **       *****    *    **  *       *     * **  ** 

gibbon           ACCCTCAAACCAACAAACCCCAAGCCCTTCAGAACACCCCAAACGACGCAACCCCAAAAC
orangutan        ACCTCCAAACCAACAGATTCCAACTCCCCCCATACACCCTCAACGATACAACCCCAAATC
sumatran         ACCTCCAAACCAGCAAATTCTAACTCCTCTCATACACCCTCAACAACACAACCCCAAACC
gorilla          GCCTTCAGGCTAACAAATCTCAACCACTTCCAAACATTTCCCATAGTACAACCCGAGAAT
homosapiens      ACCCTGAAATCAACAAACCTTAACCACTCCCGAACACCCCTAACAACATAACCCCAAAAC
chimpanzee       ACTTCGAGATTAACAAATCTCAACCACCCCCAAATACTCCCGGCAATACAACCCCGAAAC
bonobo           ACTTCAAGATTAACAAACCTCAACCACTCCCAAATACTCCCGACAACACAACCCCGAAAC
                  *    *    * ** *    **   *      * *             *****   *  

gibbon           AACCCACCCACCACTATATATACCCACCCAACTCGACCTACACCAATCCCCACATAGCAC
orangutan        AAACCACCATCCAATTAATCCACCCGTCCACACCAACCAACACCAACCCCCACCTACTAT
sumatran         AAACCACCACCCAGTTAATCCACCCATCTACACCAGCCAACACCAACCCCCACCTACTAT
gorilla          AAGCTACCATCCACTAAATCCATTTATCCATAAAAACCAACACCAACCCCCATCTAACAC
homosapiens      AAGCTACTACCCGCCAAACCCACTCACCCATACAAACCAACACCACTCTCCACCTAATAT
chimpanzee       AAGCTACTACCCACCAAACCCATCCACCCATACAAACCAACATTACCCTCCATCCAATAT
bonobo           AAGCTACTACCCACCAAACCCACTTACCCATACAAACCAACATCACCCTCCATCCAATAT
                 ** * **   **     *   *     * *      ** ***  *  * ***   *  * 

gibbon           ACAGACCAACAACCTCCCACCTTCCATACCAAGCCCCGACTTTACCGCCAACGCACTTCA
orangutan        ACCGACCAATAACCTCTCAACCCCAAAGCCAAACACTATCCCCAAAACCAACACACCCCA
sumatran         ACCAACCAATAACCTCTCAACCCCAAAACCAAACACTATCCCCAAAACCAACACACTCTA
gorilla          ACAAACTAATGACCCCCCACCCTCAAAGCCAAACACCAACCCTATAATCAATACGCCTTA
homosapiens      ACAAATTAATAACCTCCCACCTTCAGAACTGAACACCAATCTCATAACCAACACACCCCA
chimpanzee       ACAAACTAACGACCTCCCACTCTTCAGACCGAACACCAATCTCACAACCAACACGCCCCG
bonobo           ACAAACTAACAACCCCCCACCCTTCAAACCGAACACCAATTCCACAACCAATACGCCCCG
                 **  *  **  *** * **         *  * * *       *    ***  * *    

gibbon           TCAAAACATACCTACAACACAAACAAATGCCCCCCCACCCTCCTTCCCCATCAGACTCAC
orangutan        CCAAAACACACCCCCAACTCATACCCGCACACTCCCACCCCCCTTGTCTATCAAACCAAC
sumatran         CCAAAATACATCCCCAATTCATACCCGCACACCTCCGCCCCCCCTATCCATCAAACCAAC
gorilla          TCAAAACACACCCCCAACATAAACCCACGCACCCCCACCCCTTCCGTTCACTAAATCCAT
homosapiens      TCAAAACACCCCTCCAACACAAACCCGCACACCTCCACCCCCCTCGCTCATTAAATCCAT
chimpanzee       TCAAAACACCCCTTCAGCACAAACTCATACACCCCTACCTTTCCTATTTATTAAATCCAT
bonobo           TCAAAACACCCCTTCAACACAAACTCATACACCCCCACCTTTTCTATTTATTAAATCCAT
                  ***** *   *  **    * **     * *  *  **          *  * *   * 

gibbon           ACAACCTACCACCAACGGAAAAAACCGTCTACACACCCACCTGTCTACTTCCAGAACACA
orangutan        ACGACCCACAACCAACAGAAGAAACTACCCACCCCCTCACCCACCCACCTCCAAAACCCG
sumatran         ACAACCCACAATTAATAAAAAAAGCTATTCACCCCCTCATCCACCCACCTCCAAAACCCA
gorilla          AAAAGCTACAACCAACAAAAAAAACTATTCACCTCCCCATCTACCCACTTCTAAAACACA
homosapiens      AAAAATCACCACCAACAAAAAAGACTATTCACCCCCCCACTTGTTCATTCCCAAGACACA
chimpanzee       AAAAATCACAATCAACAAAAAAAGCCACCCACCTTCCCACTTACCCACTTCCAAAATAAA
bonobo           AAAAACCACAATTAACAAAAAAAACCACCCACCTCCCCACTTACCCACTTCCGAAATAAA
                 *  *   ** *  **   ** *  *     **   * **       *   *    *    

gibbon           ACACTCACCACCCCCACACACTCTCTACCATCAAACGCACAACTTACACATACAGAACCA
orangutan        ACACCCACCACCCCCACGTACCACCTTCCTCAAAATCCAGAACCCACATAACCAAGACAA
sumatran         ACACCTACCACCCCCACATACCACCTTCCTCAAAATCCAAAACCCACACAACCGAAACAA
gorilla          ACACTCATTTCTAACACGCACCACCTCCCCCCAAATACACAATTCACACAAACAATACCA
homosapiens      ACACCCATCACCATCACACACCACCTTCTCCCAAACGCACAATTCGCACACACAACGCCA
chimpanzee       ATACTCATCACCATCACACACCACCTCTCTCCAAACACACAATTCGCACAAACAACACCG
bonobo           ATACTCGTCACCATTACACACCGCCTCTCTCCAAACACACAATTCACGCAAACAACGCCA
                 * **      *    **  **   **      ***  ** **    *  *  *    *  

gibbon           CCAACCCCAACCCCAACCCACTAACAAACACACACCCGCCATACCCCCAAACATCCCCGT
orangutan        CTATCCCCAACCCAAGCCCATTAGTAAGTACACACCCACCACCCCCATCATCACTCCCAC
sumatran         CCATCCCCAACCCAAACCTACTAATAAGTACACACCCATCACCTTCACCATCACTCTCAC
gorilla          CTAATTCCAATCTAAGCCAACCAACAAATACACCCCCACCACGCCTACCAACACCTTCGT
homosapiens      CCAACCCCAACCTAAGCTAGCCAACAGATACACACTTGCCATACTCATCGACATCTCCAC
chimpanzee       CTAACTCCAATCCAAGCTAACCAACAAATACACCCCCACCACATCCATTAACACCTCCAC
bonobo           CTAACCTCAATCCAAGCTAACCAACAAACACACACCCACCATATCCATCAACACCTTCAC
                 * *    *** *  * *     *  *   **** *    **          **    *  

gibbon           ACCCCAACAACACTCATCAACCAAGTCCACCGACACCCCCCCCTTACAAATCCCCCGAAA
orangutan        ACCCCAGCAACACCACTTAATCAACCCAACTAACACCTCCCTCCCGCAAACCACCCAAAA
sumatran         ACCCCAGCAGCACCGCTTAACCAACCCGATTAACACTTCCTTCCCGTAAACCACCCAGAA
gorilla          ACTCCAATGATATTACTCAACTAACCCAACCAATACCTTTCTTTCACAAATCACCCAACA
homosapiens      AGCCCAGCAATACCGCCTAACCAATCCAACTAACACCTCCTCTCCCCAAATCACCCAACA
chimpanzee       ACCCCAACAATACTACTCAGCCAATCCAACCAACATCTCTTTTTCACAAATCACCCAATA
bonobo           ACCTCAAAAATACTACTCAGCCAATCCAACCAACATCCCTCTTTCACAAACCACCCAACC
                 *   **     *      *   **  * *   * *            *** * ***    

gibbon           AAACTAGACTTAGAGAAACATGACCATTACAACGCTCACACTACCACACATCACCCCCTA
orangutan        AAACTAAAACCACATCAACAACTTCAACACAGCACACCTATTACCGCACACCACCCCCCA
sumatran         AAACCAAAACCACATCAACAACTCCAACACAACACCCACATCACCGCGTGCCACCCTCAA
gorilla          AAATCATATCCAAAACAATAACCCCACCGCAACCCCCACACCACTACGAGCCACCCCCTA
homosapiens      AAACCAAACCCAAAACAACAATCCCACCACAACCCACACACCACTATAAACCACCCCCCA
chimpanzee       AAACTAAACCCAAAACAATAACTCCACCACAACTCTTACACCACCACAAACCACCCCCCA
bonobo           AAACTAAACCCAAAACAACAACTCCACCACAACTCCTACACCACCACAAACCACCCCCCA
                 ***  * *   * *  ** *    **   ** * *    *  **       ***** * *

gibbon           AACCAACACTAACATTCCCACAACTCAAACTCAACAACTCCCAACAGGCATCCCAACATC
orangutan        GACCAATACTAACAATTCTACAACCCTAACCTGACACCCCATAAGTAACATCTTGACCCC
sumatran         AACCATCACTAACAGCCCCGCAACCCCAACCTGACATCCCATAAATAGCATCTCGACCCC
gorilla          AACCAATATTAACACTTTTACGACCTCAATTCAACACCCTACAAGCAACATCCCAATACC
homosapiens      AATCAACATAAACACTCCTGCAACCCTAATCCAACACCCTATAAACAATACCCCAACGCC
chimpanzee       AGTCAACATCGACACTCCCACAACCCCAATCCAACGCCCTACAAACAATACTCCAACTCC
bonobo           AATCAACATCGACACTCCCACAACCCTAATCCAACACCCTATAAACAACACTCCAACGCC
                    **  *   ***      * **   **    **  *    **     *     *   *

gibbon           CCTCCCACGACATTACTTTCTCTAGCCAAAACGTAGGCCCACCACCTCCATAAGCCTACC
orangutan        CCTCCTACCACGTTACCCCCCCCAACCAAAAAACACACACACCCTTCCACCAAACCTACC
sumatran         CCCCCCACTACATTGCCCCCCCTGACCAAAAAACACACACACCCTCCCACCAAACCCACC
gorilla          CCCTCTACAATACCACTCTCCTTGACCAAAATGCACACTTACCACTCCAAAAAATTCACC
homosapiens      TCCCCCACAATGCCGCCCCCTCTAATTAAAAAACACATCTACCCCTCCAAAAAATCCATC
chimpanzee       CCCTCCACAACACCACTTCCCTTGACTAAAAAACACACCTACCCCTGCAAAAAACCCATC
bonobo           CCTTTCACAATACCACTCCCCCTAACTAAAAAACACACCCACCCCTCCAAAAAATCCATC
                  *    ** *     *   *       ****   *     ***    *   **    * *

gibbon           CCATTTCATACAACCCCACACATCTCTCAACCCCCAATCCCAACACCCACACCCCGCCAC
orangutan        CCACTCCACACAACCCCACATCTCCCCCAACCCCCAACCCCTACACCCACGCTCCACTAC
sumatran         CCACCTCGCACACTCCCACGTCTCCCCCAACCCCTAACCCCTACACCCACACTCTACCGC
gorilla          CCACCCCACACAACACCGCAACTCCCCTTGTCCCTAACTCCGATATCCACTCCCCATTAC
homosapiens      TCACCCCACACAACACCACATTTCCTCCGACCTCTAATTCCAATATCCTCTTCTCACTAC
chimpanzee       CCACCCCACTCAACACCACATTTCCCCTGACCCCCAACCCCAATATCCACCCCTCACTAC
bonobo           CCACCCCATACAACACCACATTTCCCCCAACCCCCAATCCCAATATCCACCTCTCACTAC
                  **   *   **   ** *   **       * * **  ** * * ** *         *

gibbon           AACACCAACTCCTCCTCTCCTCAGACACCAAAACACCCCACCAATTCTCCCAAACCCCCC
orangutan        CGGACACAATTCCCCCCTCCACAAACCTCTACACATCCCATCAACACACCCACACCCCCC
sumatran         TGAACACAACACCCCCCTACGCAAACCTCAACATATCCCATCAACACACCCACACCTCCC
gorilla          AATACGTAACCCCCCCCTACACAGACATCAATATACCTCAACGACACCCCCACATCCCCA
homosapiens      GACACACAATCTTCCTCCACCCAAACCCCAACACCTCTCAATAACACCCCCACACCTCCA
chimpanzee       ACTACATAATCTCCCTCCATTCAGATCTCAATACACTTCAATAACACCCTTACACCTCTA
bonobo           AGCACATAATCTCCCTCCATTCAGATCTCGACACACTTCAATAACACCCTTGCACTCCTA
                    **  *     ** *    ** *   * * *     **   *  * *    *   *  

gibbon           CCCCCCATTCACACAAACAACACAAAAAACA
orangutan        CTACTCACTCACACACACAACGTAAAAAACA
sumatran         CCACCCACTCACACACACAACACAAAAAACA
gorilla          CCATCTACTCATATACACCACATAAAAAACA
homosapiens      CCACCTACTTGCACGCACCACACAAAGAATA
chimpanzee       CCGCCTACTTACACACATTACGCAAGAAATA
bonobo           CCACCTACTCACACGCACTACGCAAAAAACA
                 *     * *   *   *  **  **  ** *
